name: Go build and test
env:
  GO111MODULE: "on"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
     #   go-version: 1.18.0-rc1
     #   go-version: 1.18.0
     #   go-version: 1.19.0
        go-version: 1.20.2
     #   stable: false
      
    - name: Build
      run: |
        cd src
        go build -o . -v ./...
        pwd
        ./jacobin -h

    - name: Test
      run: |
        export JACOBIN_HOME=`pwd`
        export JACOBIN_TESTDATA=$JACOBIN_HOME/testdata
        cd src
        export JACOBIN_EXE=`pwd`/jacobin 
        go test -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v3
